import os
import datetime
from fpdf import FPDF

# ── Colour palette ─────────────────────────────────────────────────────────────
_BG        = (14,  17,  23)   # #0e1117
_CARD      = (26,  29,  39)   # #1a1d27
_BORDER    = (42,  45,  58)   # #2a2d3a
_TEXT      = (225, 232, 240)  # #e1e8f0
_MUTED     = (107, 114, 128)  # #6b7280
_RED       = (239, 68,  68)   # deal killer
_ORANGE    = (249, 115, 22)   # critical
_YELLOW    = (234, 179, 8)    # moderate
_GREEN     = (34,  197, 94)   # manageable
_BLUE      = (59,  130, 246)  # info

_TIER_COLORS = {
    "deal_killer": _RED,
    "critical":    _ORANGE,
    "moderate":    _YELLOW,
    "manageable":  _GREEN,
    "unscored":    _MUTED,
}


def _tier_color(tier_val: str):
    return _TIER_COLORS.get(str(tier_val), _MUTED)


def _score_color(score: float):
    if score >= 75: return _RED
    if score >= 50: return _ORANGE
    if score >= 25: return _YELLOW
    return _GREEN


def _safe(text: str) -> str:
    return (text
        .replace("—", "-")
        .replace("–", "-")
        .replace("…", "...")
        .replace("‘", "'").replace("’", "'")
        .replace("“", '"').replace("”", '"')
        .encode("latin-1", errors="replace").decode("latin-1")
    )


def _fmt(val) -> str:
    if val is None:
        return "-"
    return str(val).replace("_", " ").title()


class _PDF(FPDF):
    def __init__(self, target: str, scan_date: str):
        super().__init__()
        self._target    = target
        self._scan_date = scan_date

    def header(self):
        self.set_fill_color(*_BG)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*_RED)
        self.set_xy(10, 4)
        self.cell(20, 8, "RedFlag", ln=0)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*_MUTED)
        self.cell(0, 8, _safe(f"M&A Cybersecurity Due Diligence  -  {self._target}  -  {self._scan_date}"), ln=0, align="R")
        self.set_draw_color(*_BORDER)
        self.line(0, 18, 210, 18)
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_MUTED)
        self.set_fill_color(*_BG)
        self.rect(0, self.get_y() - 2, 210, 16, "F")
        self.cell(0, 8, _safe(f"CONFIDENTIAL - Generated by RedFlag  -  Page {self.page_no()}"), align="C")

    def _section_heading(self, text: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_MUTED)
        self.set_fill_color(*_BG)
        self.cell(0, 6, text.upper(), ln=True, fill=True)
        self.set_draw_color(*_BORDER)
        self.line(self.get_x(), self.get_y(), 200, self.get_y())
        self.ln(3)

    def _metric_box(self, x, y, w, h, label, value, color):
        self.set_fill_color(*_CARD)
        self.set_draw_color(*color)
        self.rect(x, y, w, h, "FD")
        # top accent line
        self.set_fill_color(*color)
        self.rect(x, y, w, 1.2, "F")
        self.set_xy(x, y + 3)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(w, 4, label.upper(), align="C", ln=True)
        self.set_xy(x, y + 8)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*color)
        self.cell(w, 10, str(value), align="C", ln=True)

    def _finding_row(self, f, is_shade: bool):
        tier_val  = str(getattr(f.deal_tier, "value", f.deal_tier))
        tc        = _tier_color(tier_val)
        sc        = _score_color(f.risk_score)
        fill      = (20, 22, 30) if is_shade else (16, 18, 25)

        row_h = 7
        x0    = self.get_x()
        y0    = self.get_y()

        if y0 > 265:
            self.add_page()
            y0 = self.get_y()

        self.set_fill_color(*fill)
        self.rect(x0, y0, 190, row_h, "F")

        # Tier dot
        self.set_fill_color(*tc)
        self.ellipse(x0 + 2, y0 + 2.5, 2.5, 2.5, "F")

        # Title (truncated)
        title = _safe(f.title if len(f.title) <= 52 else f.title[:49] + "...")
        self.set_xy(x0 + 6, y0 + 1)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*_TEXT)
        self.cell(82, row_h - 2, title, ln=0)

        # Host:Port
        host_str = _safe(f"{f.host or '-'}:{f.port}" if f.port else (f.host or "-"))
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(32, row_h - 2, host_str, ln=0)

        # Scanner
        src = str(getattr(f.scanner_source, "value", f.scanner_source)).upper()
        self.cell(18, row_h - 2, src, ln=0)

        # CVSS
        self.cell(14, row_h - 2, f"{f.cvss_score:.1f}", ln=0, align="C")

        # Evidence
        ev = str(getattr(f.evidence_strength, "value", f.evidence_strength)).title()
        self.cell(22, row_h - 2, ev, ln=0)

        # Risk score
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*sc)
        self.cell(16, row_h - 2, f"{f.risk_score:.1f}", ln=0, align="R")

        self.ln(row_h)


def generate_cost_section(
    pdf_path: str,
    rollup,
    narrative_text: str = "",
) -> str:
    """
    Append a Cost & Remediation Budget section to an existing PDF report.

    Args:
        pdf_path:       path to the PDF already generated by generate_pdf_report()
        rollup:         CostRollup object
        narrative_text: optional narrative paragraph to include

    Returns:
        Path to the modified PDF (same as pdf_path).

    Note: fpdf2 does not support appending to existing PDFs.  This function
    generates a *separate* cost-section PDF and returns its path.
    The caller may concatenate the two PDFs using a library such as pypdf2
    if a single merged file is needed.  For now it produces cost_{original}.pdf.
    """
    import os

    dirname  = os.path.dirname(pdf_path)
    basename = os.path.basename(pdf_path)
    out_path = os.path.join(dirname, "cost_" + basename)

    target   = getattr(rollup, "target", "")
    scan_dt  = datetime.datetime.utcnow().strftime("%Y-%m-%d")

    pdf = _PDF(target, scan_dt)
    pdf.set_auto_page_break(auto=True, margin=15)

    # Set dark background
    pdf.set_fill_color(*_BG)
    pdf.set_text_color(*_TEXT)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_RED)
    pdf.cell(0, 10, "Cost & Remediation Budget", ln=True)
    pdf.set_draw_color(*_BORDER)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # Narrative paragraph
    if narrative_text:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_TEXT)
        pdf.multi_cell(190, 5, _safe(narrative_text))
        pdf.ln(4)

    # Summary totals
    pdf._section_heading("Cost Summary (USD)")

    totals = [
        ("Total Low",  rollup.total.low,       _GREEN),
        ("Total Base", rollup.total.base,       _TEXT),
        ("Total High", rollup.total.high,       _RED),
        ("CapEx",      rollup.capex_total.base, _YELLOW),
        ("OpEx",       rollup.opex_total.base,  _BLUE),
    ]

    x_start = 10
    box_w   = 36
    box_h   = 22
    for i, (label, val, color) in enumerate(totals):
        pdf._metric_box(x_start + i * (box_w + 2), pdf.get_y(), box_w, box_h, label, f"${val:,.0f}", color)

    pdf.set_y(pdf.get_y() + box_h + 6)

    # Line items table
    pdf._section_heading(f"Remediation Line Items  ({len(rollup.line_items)})")

    headers = [("Title", 70), ("Category", 28), ("CE/OE", 16), ("Low", 22), ("Base", 22), ("High", 22), ("Flags", 10)]
    pdf.set_fill_color(*_CARD)
    pdf.rect(10, pdf.get_y(), 190, 7, "F")
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_text_color(*_MUTED)
    pdf.set_x(10)
    for col, w in headers:
        pdf.cell(w, 7, col, ln=0, align="L" if col == "Title" else "C")
    pdf.ln(7)

    for idx, item in enumerate(rollup.line_items):
        fill = (20, 22, 30) if idx % 2 == 0 else (16, 18, 25)
        y0 = pdf.get_y()
        if y0 > 265:
            pdf.add_page()
            y0 = pdf.get_y()

        has_flags = item.needs_review
        row_color = _RED if has_flags else _TEXT

        pdf.set_fill_color(*fill)
        pdf.rect(10, y0, 190, 7, "F")
        pdf.set_x(10)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*row_color)

        title_short = item.title[:55] + ("..." if len(item.title) > 55 else "")
        cat = str(getattr(item.category, "value", item.category)).replace("_", " ").title()
        ce  = str(getattr(item.capex_opex, "value", item.capex_opex)).upper()

        pdf.cell(70, 5, _safe(title_short), ln=0)
        pdf.cell(28, 5, _safe(cat[:18]),    ln=0, align="C")
        pdf.cell(16, 5, ce,                 ln=0, align="C")
        pdf.cell(22, 5, f"${item.cost.low:,.0f}",  ln=0, align="R")
        pdf.cell(22, 5, f"${item.cost.base:,.0f}", ln=0, align="R")
        pdf.cell(22, 5, f"${item.cost.high:,.0f}", ln=0, align="R")
        flag_str = "!" if has_flags else ""
        pdf.set_text_color(*(_RED if has_flags else _MUTED))
        pdf.cell(10, 5, flag_str, ln=0, align="C")
        pdf.ln(7)

    pdf.output(out_path)
    return out_path


def generate_pdf_report(
    findings: list,
    target: str,
    resolved_ip: str,
    scan_date: str | None = None,
    output_dir: str = "data/results",
) -> str:
    os.makedirs(output_dir, exist_ok=True)

    if scan_date is None:
        scan_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(output_dir, f"redflag_report_{timestamp}.pdf")

    # Pre-compute summary counts
    tier_counts: dict[str, int] = {}
    for f in findings:
        t = str(getattr(f.deal_tier, "value", f.deal_tier))
        tier_counts[t] = tier_counts.get(t, 0) + 1

    n_total = len(findings)
    n_dk    = tier_counts.get("deal_killer", 0)
    n_crit  = tier_counts.get("critical",    0)
    n_mod   = tier_counts.get("moderate",    0)
    n_man   = tier_counts.get("manageable",  0)

    pdf = _PDF(target=target, scan_date=scan_date)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_fill_color(*_BG)
    pdf.add_page()

    # ── Cover block ───────────────────────────────────────────────────────────
    pdf.set_fill_color(*_BG)
    pdf.rect(0, 18, 210, 50, "F")

    pdf.set_xy(10, 24)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*_TEXT)
    pdf.cell(0, 10, "RedFlag", ln=True)

    pdf.set_x(10)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 7, "Cybersecurity Due Diligence Report", ln=True)

    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_TEXT)
    pdf.cell(30, 6, "Target:", ln=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 6, f"{target}  ({resolved_ip})", ln=True)

    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*_TEXT)
    pdf.cell(30, 6, "Generated:", ln=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 6, scan_date, ln=True)

    pdf.ln(6)

    # ── Summary metric boxes ──────────────────────────────────────────────────
    pdf._section_heading("Executive Summary")

    bw, bh, gap = 34, 22, 4
    bx = 10
    by = pdf.get_y()
    for label, value, color in [
        ("Total Findings", n_total, _BLUE),
        ("Deal Killers",   n_dk,    _RED),
        ("Critical",       n_crit,  _ORANGE),
        ("Moderate",       n_mod,   _YELLOW),
        ("Manageable",     n_man,   _GREEN),
    ]:
        pdf._metric_box(bx, by, bw, bh, label, value, color)
        bx += bw + gap

    pdf.set_y(by + bh + 6)

    # ── Deal-killer detail ────────────────────────────────────────────────────
    deal_killers = [f for f in findings if str(getattr(f.deal_tier, "value", f.deal_tier)) == "deal_killer"]
    if deal_killers:
        pdf._section_heading(f"Deal-Killer Findings  ({len(deal_killers)})")
        for f in deal_killers:
            if pdf.get_y() > 255:
                pdf.add_page()
            pdf.set_fill_color(*_CARD)
            pdf.set_draw_color(*_RED)
            y0 = pdf.get_y()
            pdf.rect(10, y0, 190, 1.5, "F")  # red top bar
            pdf.set_xy(10, y0 + 3)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_RED)
            pdf.cell(0, 5, _safe(f.title[:90]), ln=True)
            pdf.set_x(10)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*_MUTED)
            host_str = f"{f.host}:{f.port}" if f.port else (f.host or "—")
            cve_str  = f.cve_id or "-"
            pdf.cell(0, 5, _safe(f"Host: {host_str}   CVE: {cve_str}   CVSS: {f.cvss_score:.1f}   Score: {f.risk_score:.1f}"), ln=True)
            if f.override_reason:
                pdf.set_x(10)
                pdf.set_font("Helvetica", "I", 7.5)
                pdf.set_text_color(251, 191, 36)
                pdf.multi_cell(190, 4.5, _safe(f"Reason: {f.override_reason}"))
            pdf.set_x(10)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*_TEXT)
            desc = f.description[:280] + ("..." if len(f.description) > 280 else "")
            pdf.multi_cell(190, 4.5, _safe(desc))
            pdf.set_x(10)
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(*_ORANGE)
            pdf.cell(22, 4.5, "Remediation:", ln=0)
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(*_TEXT)
            rem = f.remediation[:220] + ("..." if len(f.remediation) > 220 else "")
            pdf.multi_cell(168, 4.5, _safe(rem))
            pdf.ln(4)

    # ── Full findings table ───────────────────────────────────────────────────
    pdf.add_page()
    pdf._section_heading(f"All Findings  ({n_total})")

    # Table header
    pdf.set_fill_color(*_CARD)
    pdf.rect(10, pdf.get_y(), 190, 7, "F")
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(*_MUTED)
    pdf.set_x(10)
    for col, w in [("Title", 88), ("Host:Port", 32), ("Scanner", 18), ("CVSS", 14), ("Evidence", 22), ("Score", 16)]:
        pdf.cell(w, 7, col, ln=0, align="L" if col not in ("CVSS", "Score") else "C")
    pdf.ln(7)

    for i, f in enumerate(findings):
        pdf._finding_row(f, i % 2 == 0)

    pdf.output(output_file)
    return output_file
